/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "my-project-messages.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(UpdateConfiguration, UpdateConfiguration, AUTO)


PB_BIND(SetUpdateConfiguration, SetUpdateConfiguration, AUTO)


PB_BIND(MyProjectCommand, MyProjectCommand, AUTO)


PB_BIND(InvalidCommandResponse, InvalidCommandResponse, AUTO)


PB_BIND(HatDetailsResponse, HatDetailsResponse, AUTO)


PB_BIND(UpdateResponse, UpdateResponse, AUTO)


PB_BIND(MyProjectResponse, MyProjectResponse, AUTO)





