/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_MY_PROJECT_MESSAGES_PB_H_INCLUDED
#define PB_MY_PROJECT_MESSAGES_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _UpdateType {
    UpdateType_UpdateType_NotSet = 0,
    UpdateType_UpdateType_None = 1,
    UpdateType_UpdateType_Interval = 2
} UpdateType;

typedef enum _NoArgCommands {
    NoArgCommands_Nac_NotSet = 0,
    NoArgCommands_Nac_ClearScreenToWhite = 1,
    NoArgCommands_Nac_ClearScreenToBlack = 2,
    NoArgCommands_Nac_GetConfiguration = 3,
    NoArgCommands_Nac_GetFirmwareDetails = 4,
    NoArgCommands_Nac_RestartDevice = 5
} NoArgCommands;

/* Struct definitions */
typedef struct _UpdateConfiguration {
    UpdateType updateType;
    uint32_t updateIntervalInMs;
} UpdateConfiguration;

typedef struct _SetUpdateConfiguration {
    bool has_updateConfiguration;
    UpdateConfiguration updateConfiguration;
    bool saveConfiguration;
} SetUpdateConfiguration;

typedef struct _HatConfiguration {
    char imagePath[40];
    bool rotateImage;
} HatConfiguration;

typedef struct _SetHatRotateImageCommand {
    bool rotateImage;
} SetHatRotateImageCommand;

typedef struct _SetHatImageCommand {
    char imagePath[40];
} SetHatImageCommand;

typedef struct _GetDgsrImageValidationResultCommand {
    char imagePath[40];
} GetDgsrImageValidationResultCommand;

typedef struct _MyProjectCommand {
    pb_size_t which_command;
    union {
        NoArgCommands noArgCommand;
        SetHatImageCommand setHatImage;
        SetHatRotateImageCommand setHatRotateImage;
        GetDgsrImageValidationResultCommand getDgsrImageValidationResult;
    } command;
} MyProjectCommand;

typedef struct _InvalidCommandResponse {
    char message[50];
} InvalidCommandResponse;

typedef struct _ConfigurationResponse {
    bool has_updateConfiguration;
    UpdateConfiguration updateConfiguration;
    bool has_hatConfiguration;
    HatConfiguration hatConfiguration;
} ConfigurationResponse;

typedef struct _FirmwareDetailsResponse {
    char version[30];
    char buildTime[30];
} FirmwareDetailsResponse;

typedef struct _UpdateResponse {
    uint32_t boardUptimeInMs;
} UpdateResponse;

typedef struct _SetHatImageResponse {
    char imagePath[40];
    bool success;
    char message[100];
} SetHatImageResponse;

typedef struct _GetDgsrImageValidationResultResponse {
    char imagePath[40];
    bool isValid;
    char message[100];
} GetDgsrImageValidationResultResponse;

typedef struct _MyProjectResponse {
    pb_size_t which_response;
    union {
        InvalidCommandResponse invalidCommandResponse;
        FirmwareDetailsResponse firmwareDetailsResponse;
        UpdateResponse updateResponse;
        ConfigurationResponse configurationResponse;
        SetHatImageResponse setHatImageResponse;
        GetDgsrImageValidationResultResponse getDgsrImageValidationResultResponse;
    } response;
} MyProjectResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _UpdateType_MIN UpdateType_UpdateType_NotSet
#define _UpdateType_MAX UpdateType_UpdateType_Interval
#define _UpdateType_ARRAYSIZE ((UpdateType)(UpdateType_UpdateType_Interval+1))

#define _NoArgCommands_MIN NoArgCommands_Nac_NotSet
#define _NoArgCommands_MAX NoArgCommands_Nac_RestartDevice
#define _NoArgCommands_ARRAYSIZE ((NoArgCommands)(NoArgCommands_Nac_RestartDevice+1))

#define UpdateConfiguration_updateType_ENUMTYPE UpdateType






#define MyProjectCommand_command_noArgCommand_ENUMTYPE NoArgCommands









/* Initializer values for message structs */
#define UpdateConfiguration_init_default         {_UpdateType_MIN, 0}
#define SetUpdateConfiguration_init_default      {false, UpdateConfiguration_init_default, 0}
#define HatConfiguration_init_default            {"", 0}
#define SetHatRotateImageCommand_init_default    {0}
#define SetHatImageCommand_init_default          {""}
#define GetDgsrImageValidationResultCommand_init_default {""}
#define MyProjectCommand_init_default            {0, {_NoArgCommands_MIN}}
#define InvalidCommandResponse_init_default      {""}
#define ConfigurationResponse_init_default       {false, UpdateConfiguration_init_default, false, HatConfiguration_init_default}
#define FirmwareDetailsResponse_init_default     {"", ""}
#define UpdateResponse_init_default              {0}
#define SetHatImageResponse_init_default         {"", 0, ""}
#define GetDgsrImageValidationResultResponse_init_default {"", 0, ""}
#define MyProjectResponse_init_default           {0, {InvalidCommandResponse_init_default}}
#define UpdateConfiguration_init_zero            {_UpdateType_MIN, 0}
#define SetUpdateConfiguration_init_zero         {false, UpdateConfiguration_init_zero, 0}
#define HatConfiguration_init_zero               {"", 0}
#define SetHatRotateImageCommand_init_zero       {0}
#define SetHatImageCommand_init_zero             {""}
#define GetDgsrImageValidationResultCommand_init_zero {""}
#define MyProjectCommand_init_zero               {0, {_NoArgCommands_MIN}}
#define InvalidCommandResponse_init_zero         {""}
#define ConfigurationResponse_init_zero          {false, UpdateConfiguration_init_zero, false, HatConfiguration_init_zero}
#define FirmwareDetailsResponse_init_zero        {"", ""}
#define UpdateResponse_init_zero                 {0}
#define SetHatImageResponse_init_zero            {"", 0, ""}
#define GetDgsrImageValidationResultResponse_init_zero {"", 0, ""}
#define MyProjectResponse_init_zero              {0, {InvalidCommandResponse_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define UpdateConfiguration_updateType_tag       1
#define UpdateConfiguration_updateIntervalInMs_tag 2
#define SetUpdateConfiguration_updateConfiguration_tag 1
#define SetUpdateConfiguration_saveConfiguration_tag 2
#define HatConfiguration_imagePath_tag           1
#define HatConfiguration_rotateImage_tag         2
#define SetHatRotateImageCommand_rotateImage_tag 1
#define SetHatImageCommand_imagePath_tag         1
#define GetDgsrImageValidationResultCommand_imagePath_tag 1
#define MyProjectCommand_noArgCommand_tag        1
#define MyProjectCommand_setHatImage_tag         2
#define MyProjectCommand_setHatRotateImage_tag   3
#define MyProjectCommand_getDgsrImageValidationResult_tag 4
#define InvalidCommandResponse_message_tag       1
#define ConfigurationResponse_updateConfiguration_tag 1
#define ConfigurationResponse_hatConfiguration_tag 2
#define FirmwareDetailsResponse_version_tag      1
#define FirmwareDetailsResponse_buildTime_tag    2
#define UpdateResponse_boardUptimeInMs_tag       1
#define SetHatImageResponse_imagePath_tag        1
#define SetHatImageResponse_success_tag          2
#define SetHatImageResponse_message_tag          3
#define GetDgsrImageValidationResultResponse_imagePath_tag 1
#define GetDgsrImageValidationResultResponse_isValid_tag 2
#define GetDgsrImageValidationResultResponse_message_tag 3
#define MyProjectResponse_invalidCommandResponse_tag 1
#define MyProjectResponse_firmwareDetailsResponse_tag 2
#define MyProjectResponse_updateResponse_tag     3
#define MyProjectResponse_configurationResponse_tag 4
#define MyProjectResponse_setHatImageResponse_tag 5
#define MyProjectResponse_getDgsrImageValidationResultResponse_tag 6

/* Struct field encoding specification for nanopb */
#define UpdateConfiguration_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    updateType,        1) \
X(a, STATIC,   SINGULAR, UINT32,   updateIntervalInMs,   2)
#define UpdateConfiguration_CALLBACK NULL
#define UpdateConfiguration_DEFAULT NULL

#define SetUpdateConfiguration_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  updateConfiguration,   1) \
X(a, STATIC,   SINGULAR, BOOL,     saveConfiguration,   2)
#define SetUpdateConfiguration_CALLBACK NULL
#define SetUpdateConfiguration_DEFAULT NULL
#define SetUpdateConfiguration_updateConfiguration_MSGTYPE UpdateConfiguration

#define HatConfiguration_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   imagePath,         1) \
X(a, STATIC,   SINGULAR, BOOL,     rotateImage,       2)
#define HatConfiguration_CALLBACK NULL
#define HatConfiguration_DEFAULT NULL

#define SetHatRotateImageCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     rotateImage,       1)
#define SetHatRotateImageCommand_CALLBACK NULL
#define SetHatRotateImageCommand_DEFAULT NULL

#define SetHatImageCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   imagePath,         1)
#define SetHatImageCommand_CALLBACK NULL
#define SetHatImageCommand_DEFAULT NULL

#define GetDgsrImageValidationResultCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   imagePath,         1)
#define GetDgsrImageValidationResultCommand_CALLBACK NULL
#define GetDgsrImageValidationResultCommand_DEFAULT NULL

#define MyProjectCommand_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    UENUM,    (command,noArgCommand,command.noArgCommand),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,setHatImage,command.setHatImage),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,setHatRotateImage,command.setHatRotateImage),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,getDgsrImageValidationResult,command.getDgsrImageValidationResult),   4)
#define MyProjectCommand_CALLBACK NULL
#define MyProjectCommand_DEFAULT NULL
#define MyProjectCommand_command_setHatImage_MSGTYPE SetHatImageCommand
#define MyProjectCommand_command_setHatRotateImage_MSGTYPE SetHatRotateImageCommand
#define MyProjectCommand_command_getDgsrImageValidationResult_MSGTYPE GetDgsrImageValidationResultCommand

#define InvalidCommandResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   message,           1)
#define InvalidCommandResponse_CALLBACK NULL
#define InvalidCommandResponse_DEFAULT NULL

#define ConfigurationResponse_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  updateConfiguration,   1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  hatConfiguration,   2)
#define ConfigurationResponse_CALLBACK NULL
#define ConfigurationResponse_DEFAULT NULL
#define ConfigurationResponse_updateConfiguration_MSGTYPE UpdateConfiguration
#define ConfigurationResponse_hatConfiguration_MSGTYPE HatConfiguration

#define FirmwareDetailsResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   version,           1) \
X(a, STATIC,   SINGULAR, STRING,   buildTime,         2)
#define FirmwareDetailsResponse_CALLBACK NULL
#define FirmwareDetailsResponse_DEFAULT NULL

#define UpdateResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   boardUptimeInMs,   1)
#define UpdateResponse_CALLBACK NULL
#define UpdateResponse_DEFAULT NULL

#define SetHatImageResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   imagePath,         1) \
X(a, STATIC,   SINGULAR, BOOL,     success,           2) \
X(a, STATIC,   SINGULAR, STRING,   message,           3)
#define SetHatImageResponse_CALLBACK NULL
#define SetHatImageResponse_DEFAULT NULL

#define GetDgsrImageValidationResultResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   imagePath,         1) \
X(a, STATIC,   SINGULAR, BOOL,     isValid,           2) \
X(a, STATIC,   SINGULAR, STRING,   message,           3)
#define GetDgsrImageValidationResultResponse_CALLBACK NULL
#define GetDgsrImageValidationResultResponse_DEFAULT NULL

#define MyProjectResponse_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,invalidCommandResponse,response.invalidCommandResponse),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,firmwareDetailsResponse,response.firmwareDetailsResponse),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,updateResponse,response.updateResponse),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,configurationResponse,response.configurationResponse),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,setHatImageResponse,response.setHatImageResponse),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,getDgsrImageValidationResultResponse,response.getDgsrImageValidationResultResponse),   6)
#define MyProjectResponse_CALLBACK NULL
#define MyProjectResponse_DEFAULT NULL
#define MyProjectResponse_response_invalidCommandResponse_MSGTYPE InvalidCommandResponse
#define MyProjectResponse_response_firmwareDetailsResponse_MSGTYPE FirmwareDetailsResponse
#define MyProjectResponse_response_updateResponse_MSGTYPE UpdateResponse
#define MyProjectResponse_response_configurationResponse_MSGTYPE ConfigurationResponse
#define MyProjectResponse_response_setHatImageResponse_MSGTYPE SetHatImageResponse
#define MyProjectResponse_response_getDgsrImageValidationResultResponse_MSGTYPE GetDgsrImageValidationResultResponse

extern const pb_msgdesc_t UpdateConfiguration_msg;
extern const pb_msgdesc_t SetUpdateConfiguration_msg;
extern const pb_msgdesc_t HatConfiguration_msg;
extern const pb_msgdesc_t SetHatRotateImageCommand_msg;
extern const pb_msgdesc_t SetHatImageCommand_msg;
extern const pb_msgdesc_t GetDgsrImageValidationResultCommand_msg;
extern const pb_msgdesc_t MyProjectCommand_msg;
extern const pb_msgdesc_t InvalidCommandResponse_msg;
extern const pb_msgdesc_t ConfigurationResponse_msg;
extern const pb_msgdesc_t FirmwareDetailsResponse_msg;
extern const pb_msgdesc_t UpdateResponse_msg;
extern const pb_msgdesc_t SetHatImageResponse_msg;
extern const pb_msgdesc_t GetDgsrImageValidationResultResponse_msg;
extern const pb_msgdesc_t MyProjectResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define UpdateConfiguration_fields &UpdateConfiguration_msg
#define SetUpdateConfiguration_fields &SetUpdateConfiguration_msg
#define HatConfiguration_fields &HatConfiguration_msg
#define SetHatRotateImageCommand_fields &SetHatRotateImageCommand_msg
#define SetHatImageCommand_fields &SetHatImageCommand_msg
#define GetDgsrImageValidationResultCommand_fields &GetDgsrImageValidationResultCommand_msg
#define MyProjectCommand_fields &MyProjectCommand_msg
#define InvalidCommandResponse_fields &InvalidCommandResponse_msg
#define ConfigurationResponse_fields &ConfigurationResponse_msg
#define FirmwareDetailsResponse_fields &FirmwareDetailsResponse_msg
#define UpdateResponse_fields &UpdateResponse_msg
#define SetHatImageResponse_fields &SetHatImageResponse_msg
#define GetDgsrImageValidationResultResponse_fields &GetDgsrImageValidationResultResponse_msg
#define MyProjectResponse_fields &MyProjectResponse_msg

/* Maximum encoded size of messages (where known) */
#define ConfigurationResponse_size               55
#define FirmwareDetailsResponse_size             62
#define GetDgsrImageValidationResultCommand_size 41
#define GetDgsrImageValidationResultResponse_size 144
#define HatConfiguration_size                    43
#define InvalidCommandResponse_size              51
#define MY_PROJECT_MESSAGES_PB_H_MAX_SIZE        MyProjectResponse_size
#define MyProjectCommand_size                    43
#define MyProjectResponse_size                   147
#define SetHatImageCommand_size                  41
#define SetHatImageResponse_size                 144
#define SetHatRotateImageCommand_size            2
#define SetUpdateConfiguration_size              12
#define UpdateConfiguration_size                 8
#define UpdateResponse_size                      6

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
