/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "my-project-messages.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(UpdateConfiguration, UpdateConfiguration, AUTO)


PB_BIND(SetUpdateConfiguration, SetUpdateConfiguration, AUTO)


PB_BIND(HatConfiguration, HatConfiguration, AUTO)


PB_BIND(SetHatRotateImageCommand, SetHatRotateImageCommand, AUTO)


PB_BIND(SetHatImageCommand, SetHatImageCommand, AUTO)


PB_BIND(GetDgsrImageValidationResultCommand, GetDgsrImageValidationResultCommand, AUTO)


PB_BIND(MyProjectCommand, MyProjectCommand, AUTO)


PB_BIND(InvalidCommandResponse, InvalidCommandResponse, AUTO)


PB_BIND(ConfigurationResponse, ConfigurationResponse, AUTO)


PB_BIND(FirmwareDetailsResponse, FirmwareDetailsResponse, AUTO)


PB_BIND(UpdateResponse, UpdateResponse, AUTO)


PB_BIND(SetHatImageResponse, SetHatImageResponse, AUTO)


PB_BIND(GetDgsrImageValidationResultResponse, GetDgsrImageValidationResultResponse, AUTO)


PB_BIND(MyProjectResponse, MyProjectResponse, AUTO)





